/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/createpost`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/CreateAccount` | `/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signIn` | `/signIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Create` | `/Create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Discover` | `/Discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Events` | `/Events`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventBanner`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventDescription`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventTitle`; params?: Router.UnknownInputParams; } | { pathname: `/components/RSVPButton`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/createpost`; params?: Router.UnknownOutputParams; } | { pathname: `/screens`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/CreateAccount` | `/CreateAccount`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signIn` | `/signIn`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Create` | `/Create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Discover` | `/Discover`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Events` | `/Events`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EventBanner`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EventDescription`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EventTitle`; params?: Router.UnknownOutputParams; } | { pathname: `/components/RSVPButton`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens/createpost${`?${string}` | `#${string}` | ''}` | `/screens${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/CreateAccount${`?${string}` | `#${string}` | ''}` | `/CreateAccount${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signIn${`?${string}` | `#${string}` | ''}` | `/signIn${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Create${`?${string}` | `#${string}` | ''}` | `/Create${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Discover${`?${string}` | `#${string}` | ''}` | `/Discover${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Events${`?${string}` | `#${string}` | ''}` | `/Events${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/EventBanner${`?${string}` | `#${string}` | ''}` | `/components/EventDescription${`?${string}` | `#${string}` | ''}` | `/components/EventTitle${`?${string}` | `#${string}` | ''}` | `/components/RSVPButton${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens/createpost`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/CreateAccount` | `/CreateAccount`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signIn` | `/signIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Create` | `/Create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Discover` | `/Discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Events` | `/Events`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventBanner`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventDescription`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventTitle`; params?: Router.UnknownInputParams; } | { pathname: `/components/RSVPButton`; params?: Router.UnknownInputParams; };
    }
  }
}
