/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EventPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/createpost`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventPicture`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventBanner`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventDesc`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/EventPage`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/createpost`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EventPicture`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EventBanner`; params?: Router.UnknownOutputParams; } | { pathname: `/components/EventDesc`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens${`?${string}` | `#${string}` | ''}` | `/screens/EventPage${`?${string}` | `#${string}` | ''}` | `/screens/createpost${`?${string}` | `#${string}` | ''}` | `/components/EventPicture${`?${string}` | `#${string}` | ''}` | `/components/EventBanner${`?${string}` | `#${string}` | ''}` | `/components/EventDesc${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EventPage`; params?: Router.UnknownInputParams; } | { pathname: `/screens/createpost`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventPicture`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventBanner`; params?: Router.UnknownInputParams; } | { pathname: `/components/EventDesc`; params?: Router.UnknownInputParams; };
    }
  }
}
